### PR TITLE
Add credits to convertToJSON and to readObject for WordItems (lexeme, definition, translation)

### PR DESCRIPTION
**Pull request by irina060981**
For the https://github.com/alpheios-project/components/issues/840

### CODE REVIEW

**Comment by irina060981** [comment]
tests are ready

**Comment by balmas** [comment]
hmm. this is an interesting dilemma. We originally came up with the ResourceProviderProxy wrapper on the Alpheios data model objects so that they we could keep the knowledge of the existence or not of the provider out of the data model itself. 

E.g. in the client-adapters, we add a provider to a definition by wrapping it in a ResourceProviderProxy:

```
ResourceProvider.getProxy(provider, new Definition(meaning.$, lang, 'text/plain', lemmas[index].word)))
```
I think this was a useful design pattern when we came up with it but we didn't consider at that time the need to serialize and re-retrieve these data objects when at a later time.  (And it's possible that it was just an instance of using a cool new language feature when it wasn't absolutely necessary...)   

While technically I think the changes in this PR work to solve the problem, they break the design pattern we had implemented for the ResourceProviderProxy.  

I wonder whether there are any best practices around serialization of proxied objects that we should use here, or if we should just drop the use of the proxy.  @kirlat and @irina060981 what are your thoughts?

**Comment by irina060981** [comment]
@balmas, it needs a small fix to assign provider.
I have pushed the change - I missed to use Proxy for provider.
So we need no special serialization methods for a provider property.

According to the usage of Proxy object. 
I think that it is a nice modern metaprogramming feature but I don't see the practical advantages of the Proxy's handlers in our current architecture. 

I believe that we have the same result - showing a `provider` object through `Proxy` or assigning `provider` as a reference (because it is an object).
It seems to me when we assign provider - than it would be destroyed and collected with garbarge, when all objects with its reference would be deleted.
As for Proxy it (provider variable that is hidden inside Proxy) should be destroyed (I believe) when all Proxy objects would be destroyed (and it should be the same moment).

I believe that more complex constructions as Proxy in our situation could decrease performance (as it is derivative from more simple language tools as Object), but could be liked by someone who loves to use metaprogramming approach.

I like the following approach - things should be 
   as simple as possible
   as natively understandable as possible
   as independent as possible

But I am not sure that it is a preferable way to create code in mordern programming society :)

**Comment by balmas** [comment]
@irina060981 your answer makes me laugh :-)

Thanks for making the change to use the proxy here.  I guess we can go with this for now and I will enter an issue for refactoring that asks us to consider whether or not we want to keep this design.  @kirlat do you agree?

**Comment by kirlat** [comment]
> Thanks for making the change to use the proxy here. I guess we can go with this for now and I will enter an issue for refactoring that asks us to consider whether or not we want to keep this design. @kirlat do you agree?

I think this will be good. Since we now have a more complex (can I say mature 🙂?) architecture and some breathing space and time it might be good to review our ways. It would be also good, as we discussed, to standardize our approaches across the board.

**Pull request merged**
