### PR TITLE
Fix the way fullCit is constructed and added tests for it

### PR DESCRIPTION
**Pull request by irina060981**
For the issue https://github.com/alpheios-project/components/issues/631

### CODE REVIEW

**Comment by irina060981** [comment]
>And that formatting (applying of emphasis, etc.) should be done by the display component not the data model, so in order to faciliate that we need to return an object here. What do you think?

I am not sure that we really need it, because we operate with the instance of `wordUsageItem` (`WordUsageExample` class).
It has already the following properties - author, textwork.
We could simply add here a passage.
And we use it not only in calculating the fullCit.

From the other point of view - we could create additional property, fullCitParts for example and construct fullCit for any non-standard cases.

I think that we need both data - standard constructed fullCit for some cases (when we have less data to choose what would be the best format)
And parts for constructing a non-standard variant.
We have those parts as object (author and textwork), but could create a simple property with already defined parts (we choose authoe and textwork title using lang property).

**Comment by balmas** [comment]
> > And that formatting (applying of emphasis, etc.) should be done by the display component not the data model, so in order to faciliate that we need to return an object here. What do you think?
> 
> I am not sure that we really need it, because we operate with the instance of `wordUsageItem` (`WordUsageExample` class).
> It has already the following properties - author, textwork.
> We could simply add here a passage.
> And we use it not only in calculating the fullCit.
> 
> From the other point of view - we could create additional property, fullCitParts for example and construct fullCit for any non-standard cases.
> 
> I think that we need both data - standard constructed fullCit for some cases (when we have less data to choose what would be the best format)
> And parts for constructing a non-standard variant.
> We have those parts as object (author and textwork), but could create a simple property with already defined parts (we choose authoe and textwork title using lang property).

Ok, so maybe what we need are `formattedTextWork` and `formattedAuthor` methods on `WordUsageExample`, which return the results of splitting, looking up by language, etc?

**Comment by irina060981** [comment]
>Ok, so maybe what we need are `formattedTextWork` and `formattedAuthor` methods on WordUsageExample, which return the results of splitting, looking up by language, etc?

@balmas, Do you mean to add the following to wordUsageExample this get properties for now?
  - `formattedAuthor` () => this.author.title()
  - `formattedTextWork` () => this.textWork.title()

and latter it could be enlarged?

**Comment by balmas** [comment]
Truthfully, I don't care too much how we do it right now, as long as we can then display the citation formatted as I've described above, with the title in italics

E.g. Cicero, _Marcus Tullius ad Familares_ 8.4.3.1

I was suggesting the change because I didn't think the fullCit method should return HTML, but maybe that is the simplest approach for now.

**Comment by irina060981** [comment]
@balmas , I have added properties and slightly changed fullCit.
Hope it is more closer to that you meant!

**Pull request merged**
